storage: ./storage
auth:
  htpasswd:
    file: ./htpasswd
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  '@*/*':
    access: $all
    publish: $authenticated
    proxy: npmjs
  '**':
    proxy: npmjs
    access: $all
    publish: $authenticated
logs:
  - {type: stdout, format: pretty, level: http}
middlewares:
  github-oauth-ui:
    client-id: GITHUB_OAUTH_CLIENT_ID
    client-secret: GITHUB_OAUTH_CLIENT_SECRET
